---
name: Build pocketbook-ssh

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-pocketbook-ssh
  cancel-in-progress: false

jobs:
  filter-changes:
    name: Filter changes
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Build files changed
        id: build-files-changed
        uses: bjw-s-labs/action-changed-files@015416e33c709af88f84a4496f4030c1f0ef212e # v0.5.0
        with:
          patterns: |
            .github/workflows/build.yaml
            application/**
            patches/**
            Dockerfile

  build-application:
    if: ${{ needs.filter-changes.outputs.changed-files != '[]' }}
    name: Build application
    runs-on: ubuntu-latest
    needs:
      - filter-changes
    permissions:
      contents: write
    env:
      TOOLCHAIN_IMAGE: pocketbook-ssh-toolchain:latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Build image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: build
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
        with:
          push: false
          load: true
          tags: ${{ env.TOOLCHAIN_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Fetch build output
        uses: kohlerdominik/docker-run-action@170cd7d34e33265bfba818cddf461bae2d6c44d2 # v2.0.0
        with:
          image: ${{ env.TOOLCHAIN_IMAGE }}
          volumes: |
            ${{ github.workspace }}/dist:/dist
          run: |
            cp /output/pocketbook-ssh/pocketbook-ssh.zip /dist/

      - name: Release artifact
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          tag_name: "2025.87"
          body: |
            Dropbear 2025.87 for Pocketbook eReaders
          files: dist/pocketbook-ssh.zip
